version: '3.4'

services:
  elastic-logger-web-api:
    image: ${DOCKER_REGISTRY-}elasticloggerwebapi
    container_name: elasticloggerwebapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - elasticsearch
    networks:
     - docker-network

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
   container_name: elasticsearch
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - docker-network

  kibana:
   image: docker.elastic.co/kibana/kibana:6.2.4
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - docker-network
  
networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: